workflows:
  web-workflow:
    name: Web Workflow
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
    scripts:
      - name: Install dependencies
        script: flutter packages pub get
      - name: Enable web
        script: flutter config --enable-web
      - name: Testing
        script: flutter test
      - name: Build web
        script: 
          |
          flutter build web --release
          cd build/web
          7z a -r ../web.zip ./*
    artifacts:
      - build/web.zip
    publishing:
      email:
        recipients:
          - sbis1999@gmail.com