name: my_slide_puzzle
description: A Flutter slide puzzle game

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.2
  equatable: ^2.0.3
  fake_async: ^1.2.0
  flutter_bloc: ^8.0.1
  gap: ^2.0.0
  google_fonts: ^2.1.0
  intl: ^0.17.0
  just_audio: ^0.9.18
  universal_platform: ^1.0.0+1
  url_launcher: ^6.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
    - assets/images/audio_control/
    - assets/images/dashatar/gallery/
    - assets/images/dashatar/success/
    - assets/images/dashatar/green/
    - assets/images/dashatar/blue/
    - assets/images/dashatar/yellow/
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/GoogleSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/GoogleSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/GoogleSans-Italic.ttf
          weight: 400
          style: italic
